// ── Pre-built Creator Themes ──────────────────────────────────────────────────
// Apply via admin dashboard or programmatically via updateCreator()

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  preview: string; // emoji for quick visual reference
  settings: {
    theme_bg: string;
    theme_accent: string;
    theme_text: string;
    bg_type: "solid" | "gradient";
    bg_gradient_type: "linear" | "radial";
    bg_gradient_direction: string;
    bg_color_2: string;
    bg_color_3: string | null;
    show_floating_icons: boolean;
    floating_icon: string;
    floating_icon_count: number;
    show_stars: boolean;
    stars_count: number;
    stars_color: string;
    animation_speed: number;
    avatar_border_style: "solid" | "gradient" | "none";
    avatar_border_color_1: string;
    avatar_border_color_2: string;
    avatar_border_color_3: string;
    font: string;
  };
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "midnight-purple",
    name: "Midnight Purple",
    description: "Deep purple gradient with floating sparkles",
    preview: "🔮",
    settings: {
      theme_bg: "#1a0533",
      theme_accent: "#b44aff",
      theme_text: "#ffffff",
      bg_type: "gradient",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom",
      bg_color_2: "#0d0019",
      bg_color_3: null,
      show_floating_icons: true,
      floating_icon: "✨",
      floating_icon_count: 8,
      show_stars: true,
      stars_count: 40,
      stars_color: "#b44aff",
      animation_speed: 12,
      avatar_border_style: "gradient",
      avatar_border_color_1: "#b44aff",
      avatar_border_color_2: "#ff6bf5",
      avatar_border_color_3: "#b44aff",
      font: "playfair",
    },
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    description: "Warm rose-to-gold gradient, elegant and feminine",
    preview: "🌹",
    settings: {
      theme_bg: "#2d1b2e",
      theme_accent: "#e8a87c",
      theme_text: "#fff0e6",
      bg_type: "gradient",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom right",
      bg_color_2: "#1a0f1b",
      bg_color_3: null,
      show_floating_icons: true,
      floating_icon: "🌹",
      floating_icon_count: 5,
      show_stars: false,
      stars_count: 0,
      stars_color: "#ffffff",
      animation_speed: 15,
      avatar_border_style: "gradient",
      avatar_border_color_1: "#e8a87c",
      avatar_border_color_2: "#f4c6a0",
      avatar_border_color_3: "#d4836b",
      font: "playfair",
    },
  },
  {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    description: "Cool teal-to-navy gradient, clean and fresh",
    preview: "🌊",
    settings: {
      theme_bg: "#0a2e3d",
      theme_accent: "#67ECE1",
      theme_text: "#e0f7f5",
      bg_type: "gradient",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom",
      bg_color_2: "#041c26",
      bg_color_3: null,
      show_floating_icons: false,
      floating_icon: "💫",
      floating_icon_count: 0,
      show_stars: true,
      stars_count: 30,
      stars_color: "#67ECE1",
      animation_speed: 10,
      avatar_border_style: "solid",
      avatar_border_color_1: "#67ECE1",
      avatar_border_color_2: "#67ECE1",
      avatar_border_color_3: "#67ECE1",
      font: "inter",
    },
  },
  {
    id: "hot-pink",
    name: "Hot Pink",
    description: "Bold pink-to-dark gradient, high energy",
    preview: "💖",
    settings: {
      theme_bg: "#3d0a2e",
      theme_accent: "#ff2d8a",
      theme_text: "#ffffff",
      bg_type: "gradient",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom",
      bg_color_2: "#1a0414",
      bg_color_3: null,
      show_floating_icons: true,
      floating_icon: "💕",
      floating_icon_count: 6,
      show_stars: false,
      stars_count: 0,
      stars_color: "#ffffff",
      animation_speed: 10,
      avatar_border_style: "gradient",
      avatar_border_color_1: "#ff2d8a",
      avatar_border_color_2: "#ff6eb4",
      avatar_border_color_3: "#ff2d8a",
      font: "poppins",
    },
  },
  {
    id: "noir",
    name: "Noir",
    description: "Sleek black with subtle white accents, minimalist",
    preview: "🖤",
    settings: {
      theme_bg: "#0a0a0a",
      theme_accent: "#ffffff",
      theme_text: "#e0e0e0",
      bg_type: "solid",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom",
      bg_color_2: "#0a0a0a",
      bg_color_3: null,
      show_floating_icons: false,
      floating_icon: "💫",
      floating_icon_count: 0,
      show_stars: false,
      stars_count: 0,
      stars_color: "#ffffff",
      animation_speed: 10,
      avatar_border_style: "solid",
      avatar_border_color_1: "#ffffff",
      avatar_border_color_2: "#ffffff",
      avatar_border_color_3: "#ffffff",
      font: "montserrat",
    },
  },
  {
    id: "sunset-vibes",
    name: "Sunset Vibes",
    description: "Orange-to-pink warm gradient with floating fire",
    preview: "🌅",
    settings: {
      theme_bg: "#ff6b35",
      theme_accent: "#ffd700",
      theme_text: "#ffffff",
      bg_type: "gradient",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom",
      bg_color_2: "#d4145a",
      bg_color_3: "#1a0a2e",
      show_floating_icons: true,
      floating_icon: "🔥",
      floating_icon_count: 7,
      show_stars: false,
      stars_count: 0,
      stars_color: "#ffffff",
      animation_speed: 8,
      avatar_border_style: "gradient",
      avatar_border_color_1: "#ffd700",
      avatar_border_color_2: "#ff6b35",
      avatar_border_color_3: "#d4145a",
      font: "poppins",
    },
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    description: "Soft lavender gradient, dreamy and gentle",
    preview: "💜",
    settings: {
      theme_bg: "#2d2040",
      theme_accent: "#c9a0ff",
      theme_text: "#f0e6ff",
      bg_type: "gradient",
      bg_gradient_type: "radial",
      bg_gradient_direction: "circle at center",
      bg_color_2: "#1a1030",
      bg_color_3: null,
      show_floating_icons: true,
      floating_icon: "🦋",
      floating_icon_count: 5,
      show_stars: true,
      stars_count: 25,
      stars_color: "#c9a0ff",
      animation_speed: 14,
      avatar_border_style: "gradient",
      avatar_border_color_1: "#c9a0ff",
      avatar_border_color_2: "#e0c3ff",
      avatar_border_color_3: "#a07de0",
      font: "dancing-script",
    },
  },
  {
    id: "cyber-neon",
    name: "Cyber Neon",
    description: "Dark with neon green accents, cyberpunk feel",
    preview: "💚",
    settings: {
      theme_bg: "#0a0a0a",
      theme_accent: "#39ff14",
      theme_text: "#e0ffe0",
      bg_type: "gradient",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom",
      bg_color_2: "#0d1a0d",
      bg_color_3: null,
      show_floating_icons: false,
      floating_icon: "💫",
      floating_icon_count: 0,
      show_stars: true,
      stars_count: 60,
      stars_color: "#39ff14",
      animation_speed: 8,
      avatar_border_style: "solid",
      avatar_border_color_1: "#39ff14",
      avatar_border_color_2: "#39ff14",
      avatar_border_color_3: "#39ff14",
      font: "roboto",
    },
  },
  {
    id: "cherry-blossom",
    name: "Cherry Blossom",
    description: "Soft pink with floating sakura petals",
    preview: "🌸",
    settings: {
      theme_bg: "#3d1f2f",
      theme_accent: "#ffb7c5",
      theme_text: "#fff0f3",
      bg_type: "gradient",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom",
      bg_color_2: "#2a1520",
      bg_color_3: null,
      show_floating_icons: true,
      floating_icon: "🌸",
      floating_icon_count: 10,
      show_stars: false,
      stars_count: 0,
      stars_color: "#ffffff",
      animation_speed: 16,
      avatar_border_style: "gradient",
      avatar_border_color_1: "#ffb7c5",
      avatar_border_color_2: "#ff8fa3",
      avatar_border_color_3: "#ffd6e0",
      font: "poppins",
    },
  },
  {
    id: "ice-queen",
    name: "Ice Queen",
    description: "Icy blue gradient with crystalline stars",
    preview: "❄️",
    settings: {
      theme_bg: "#0a1628",
      theme_accent: "#7dd3fc",
      theme_text: "#e0f2fe",
      bg_type: "gradient",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom right",
      bg_color_2: "#172554",
      bg_color_3: null,
      show_floating_icons: true,
      floating_icon: "❄️",
      floating_icon_count: 6,
      show_stars: true,
      stars_count: 50,
      stars_color: "#7dd3fc",
      animation_speed: 12,
      avatar_border_style: "gradient",
      avatar_border_color_1: "#7dd3fc",
      avatar_border_color_2: "#bae6fd",
      avatar_border_color_3: "#38bdf8",
      font: "inter",
    },
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    description: "Warm amber-to-brown, luxury feel",
    preview: "✨",
    settings: {
      theme_bg: "#2e1a05",
      theme_accent: "#d4a44a",
      theme_text: "#fff5e0",
      bg_type: "gradient",
      bg_gradient_type: "linear",
      bg_gradient_direction: "to bottom",
      bg_color_2: "#1a0f02",
      bg_color_3: null,
      show_floating_icons: true,
      floating_icon: "✨",
      floating_icon_count: 5,
      show_stars: false,
      stars_count: 0,
      stars_color: "#ffffff",
      animation_speed: 12,
      avatar_border_style: "gradient",
      avatar_border_color_1: "#d4a44a",
      avatar_border_color_2: "#f0d080",
      avatar_border_color_3: "#b8862d",
      font: "playfair",
    },
  },
  {
    id: "electric-blue",
    name: "Electric Blue",
    description: "Deep blue with electric accents, bold and modern",
    preview: "⚡",
    settings: {
      theme_bg: "#0a0a2e",
      theme_accent: "#4d7cff",
      theme_text: "#e0e8ff",
      bg_type: "gradient",
      bg_gradient_type: "radial",
      bg_gradient_direction: "circle at top",
      bg_color_2: "#050514",
      bg_color_3: null,
      show_floating_icons: false,
      floating_icon: "💫",
      floating_icon_count: 0,
      show_stars: true,
      stars_count: 45,
      stars_color: "#4d7cff",
      animation_speed: 10,
      avatar_border_style: "gradient",
      avatar_border_color_1: "#4d7cff",
      avatar_border_color_2: "#7da0ff",
      avatar_border_color_3: "#2d5ce6",
      font: "montserrat",
    },
  },
];

export function getThemeById(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find((t) => t.id === id);
}

export function getThemeNames(): Array<{ id: string; name: string; preview: string }> {
  return THEME_PRESETS.map((t) => ({ id: t.id, name: t.name, preview: t.preview }));
}
